### ISSUE TITLE
Pre-compiled releases/docker image

### ISSUE THREAD

**Issue by dave08** [octohelm/cuemod#74]
It would be great if you could provide pre-compiled releases and a docker image... I'm sure not every dev-op is a go programmer, and to install the go toolkit just to provide a tool would be a bit funny. Also in CD environments like ArgoCD it would be nice to have somewhere to pull this from to add the tool to the deployment tools.

**Comment by morlay** [comment]
DONE. 

https://hub.docker.com/r/octohelm/cuem

binaries in github releases
